install.packages("readxl")
library(readxl)
chemical=read_xlsx("C:\\Users\\Admin\\Desktop\\R PRACTICE\\chemical.xlsx",1)
str(chemical)
head(chemical)
tail(chemical)
summary(chemical[,-1])
cor(chemical[,-1])

par(mfrow=c(1,2), pty="s") 
plot(chemical$speed, chemical$loss, pch=19)
plot(chemical$temp, chemical$loss, pch=19)
chemical.lm=lm(loss~speed+temp, data=chemical)
summary(chemical.lm)

install.packages("car")
library(car)
avPlots(chemical.lm)
anova(chemical.lm)

par(mfrow=c(1,2), pty="s") 
plot(chemical$speed, chemical.lm$resid, pch=19)
abline(h=0, lty=2)
identify(chemical$speed, chemical.lm$resid)

plot(chemical$temp, chemical.lm$resid, pch=19)
abline(h=0, lty=2)
identify(chemical$temp, chemical.lm$resid)

plot(chemical.lm$fitted, chemical.lm$resid, pch=19)
abline(h)
abline(h=0, lty=2)
identify(chemical.lm$fitted, chemical.lm$resid)

install.packages("fmsb")
library(fmsb)
VIF(lm(chemical$speed~chemical$temp, data=chemical))
VIF(lm(chemical$temp~chemical$speed, data=chemical))
cor(chemical[,-1])

install.packages("leaps")
library(leaps)
all.lm=regsubsets(loss~speed+temp,data=chemical)
(rs=summary(all.lm))
